services:
  - type: web
    name: world-cup-player-guess
    runtime: node
    buildCommand: npm install && npm run build -w backend && npm run build -w frontend && cd backend && npx prisma generate && npx prisma migrate deploy && npm run import:players
    startCommand: npm run start -w backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ZAFRONIX_API_KEY
        sync: false
